name: "beta-publish"

on:
  push:
    branches:
      - 1.2.0
  #pull-request:
  #  branches:
  #    - master

jobs:
  beta-release:
    name: beta-publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: ls and find directory
        run: \
          find . -name 'package.json'
      - name: version change to beta
        run: \
          PACKAGE_VERSION=$(cat "$GITHUB_WORKSPACE"/package.json \
            | grep version \
            | head -1 \
            | cut -d' ' -f3 \
            | sed 's/[",]//g' \
            sed 's/ //g')
          PACKAGE_VERSION_NEW="$PACKAGE_VERSION"-beta.`date +"%Y%m%d-%H%M"`
          sed -i "s/$PACKAGE_VERSION/$PACKAGE_VERSION_NEW/g" package.json
      - name: publish
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

